//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthyDecryptor.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthyDecryptor.UI.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow edit.
        /// </summary>
        public static string AllowEdit {
            get {
                return ResourceManager.GetString("AllowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        public static string Analyze {
            get {
                return ResourceManager.GetString("Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authy backup password.
        /// </summary>
        public static string AuthyPassword {
            get {
                return ResourceManager.GetString("AuthyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto. save to file.
        /// </summary>
        public static string AutoSave {
            get {
                return ResourceManager.GetString("AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decrypted.
        /// </summary>
        public static string Decrypted {
            get {
                return ResourceManager.GetString("Decrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypted tokens.
        /// </summary>
        public static string DecryptedTokens {
            get {
                return ResourceManager.GetString("DecryptedTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted file.
        /// </summary>
        public static string EncryptedFile {
            get {
                return ResourceManager.GetString("EncryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load decrypted file: {0}.
        /// </summary>
        public static string ErrorLoadDecryptedFile {
            get {
                return ResourceManager.GetString("ErrorLoadDecryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening the third-party licenses file..
        /// </summary>
        public static string ErrorOpeningLicensesFile {
            get {
                return ResourceManager.GetString("ErrorOpeningLicensesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select encrypted file.
        /// </summary>
        public static string InputFileTitle {
            get {
                return ResourceManager.GetString("InputFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON file.
        /// </summary>
        public static string JsonFile {
            get {
                return ResourceManager.GetString("JsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load decrypted file.
        /// </summary>
        public static string LoadDecrypted {
            get {
                return ResourceManager.GetString("LoadDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a token from the list on the left side to get detailed information about it. There you can also generate a QR code to set up a new authenticator app easily..
        /// </summary>
        public static string NoTokenSelectedDescription {
            get {
                return ResourceManager.GetString("NoTokenSelectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No token selected.
        /// </summary>
        public static string NoTokenSelectedTitle {
            get {
                return ResourceManager.GetString("NoTokenSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open repository.
        /// </summary>
        public static string OpenRepository {
            get {
                return ResourceManager.GetString("OpenRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output file.
        /// </summary>
        public static string OutputFileTitle {
            get {
                return ResourceManager.GetString("OutputFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save with indents.
        /// </summary>
        public static string SaveIndented {
            get {
                return ResourceManager.GetString("SaveIndented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to file.
        /// </summary>
        public static string SaveToFile {
            get {
                return ResourceManager.GetString("SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select decrypted file.
        /// </summary>
        public static string SelectDecryptedFile {
            get {
                return ResourceManager.GetString("SelectDecryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-Party Licenses.
        /// </summary>
        public static string ThirdPartyLicenses {
            get {
                return ResourceManager.GetString("ThirdPartyLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of digits.
        /// </summary>
        public static string TokenDigits {
            get {
                return ResourceManager.GetString("TokenDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        public static string TokenIssuer {
            get {
                return ResourceManager.GetString("TokenIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TokenName {
            get {
                return ResourceManager.GetString("TokenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret.
        /// </summary>
        public static string TokenSecret {
            get {
                return ResourceManager.GetString("TokenSecret", resourceCulture);
            }
        }
    }
}
